CREATE TYPE "prioridad" AS ENUM (
  'baja',
  'media',
  'alta'
);

CREATE TYPE "estado" AS ENUM (
  'sin_iniciar',
  'en_proceso',
  'ejecutada'
);

CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "apellido" varchar NOT NULL,
  "telefono" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "contrasena" varchar NOT NULL,
  "numero_documento" varchar UNIQUE NOT NULL,
  "fecha_creacion" timestamp NOT NULL DEFAULT (now()),
  "activado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "tarea" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "titulo" varchar UNIQUE NOT NULL,
  "prioridad" prioridad NOT NULL,
  "usuario_id" integer NOT NULL,
  "fecha_creacion" timestamp NOT NULL DEFAULT (now()),
  "fecha_limite" timestamp NOT NULL,
  "evidencia" varchar,
  "estado" estado NOT NULL DEFAULT 'sin_iniciar'
);

CREATE TABLE "observacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "tarea_id" integer NOT NULL,
  "contenido" varchar NOT NULL,
  "fecha_creacion" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "rol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" varchar
);

INSERT INTO "rol" ("nombre")
VALUES
  ('administrador'),
  ('empleado');

CREATE TABLE "roles_usuario" (
  "usuario_id" integer NOT NULL,
  "rol_id" integer NOT NULL,
  PRIMARY KEY ("usuario_id", "rol_id")
);

CREATE TABLE "atributo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "descripcion" varchar
);

CREATE TABLE "atributos_usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "usuario_id" integer NOT NULL,
  "atributo_id" integer NOT NULL,
  "valor" varchar NOT NULL
);

ALTER TABLE "roles_usuario" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "roles_usuario" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("id");

ALTER TABLE "tarea" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "observacion" ADD FOREIGN KEY ("tarea_id") REFERENCES "tarea" ("id");

ALTER TABLE "atributos_usuario" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id");

ALTER TABLE "atributos_usuario" ADD FOREIGN KEY ("atributo_id") REFERENCES "atributo" ("id");
